Several minor tweaks
6v6-Adjustments/6v6-adjustments-fork pull request #30
Opened 2024-04-28 16:01 UTC by ieToastie

Edits a few constants, finishes the rest of the tweaks regarding next patch's balance updates, comments excess rules to reduce overall script count and workshop load.

2024-04-28 16:31 UTC, MaxwellJung requested changes
Check doomfist cooldown logic in dev_lobby.opy and lobby.opy

Also, let's try to replace any magic numbers with constants in the codebase as we encounter them.

2024-04-28 16:31 UTC, MaxwellJung commented on src/lobby/dev_lobby.opy
> +                "ability1Cooldown%": percent(ADJ_DOOMFIST_POWER_BLOCK_COOLDOWN/OW2_DOOMFIST_POWER_BLOCK_COOLDOWN),
```suggestion
                "ability1Cooldown%": percent(ADJ_DOOMFIST_SLAM_CD/OW2_DOOMFIST_SLAM_CD),
                "ability2Cooldown%": percent(ADJ_DOOMFIST_POWER_BLOCK_COOLDOWN/OW2_DOOMFIST_POWER_BLOCK_COOLDOWN),
```
I thought ability 1 = slam and ability 2 = block in ow2

2024-04-28 16:31 UTC, MaxwellJung commented on src/lobby/dev_lobby.opy
> +                "ability1Cooldown%": percent(ADJ_DOOMFIST_POWER_BLOCK_COOLDOWN/OW2_DOOMFIST_POWER_BLOCK_COOLDOWN),
Also I would comment out the line instead of deleting it so eaiser to revert later.

2024-04-28 16:31 UTC, MaxwellJung commented on src/lobby/lobby.opy
> -                "ability1Cooldown%": percent(ADJ_DOOMFIST_SLAM_CD/OW2_DOOMFIST_SLAM_CD),
see above comment

2024-04-28 16:51 UTC, MaxwellJung approved these changes
ADJ_BAPTISTE_LAMP_HP isn't used in the codebase, so changing it has no impact yet.

2024-04-28 16:51 UTC, merged

2024-04-28 16:51 UTC, ieToastie reviewed
Looks good to me, will add constants where applicable from here on out

2024-05-01 05:32 UTC, MaxwellJung commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/6v6-Adjustments/6v6-adjustments/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: