new file for venture drill dash cooldown
6v6-Adjustments/6v6-adjustments-fork pull request #37
Opened 2024-05-03 05:23 UTC by vwade

proposed fix for venture's 6 second cooldown

    - live build cd: 8
    - tested cd: 6

    this is a small patch which will constrain venture's cooldown to 6 seconds

    - new file added: venture/drill_dash.opy

    * tested with developer build (practice range)
    * tested on internal developer build

2024-05-03 23:58 UTC, MaxwellJung commented on src/heroes/venture/drill_dash.opy
> +#!define ADJ_VENTURE_DRILL_DASH_COOLDOWN_BURROWED ADJ_VENTURE_DRILL_DASH_COOLDOWN / 2
```suggestion
#!define ADJ_VENTURE_DRILL_DASH_COOLDOWN_BURROWED (ADJ_VENTURE_DRILL_DASH_COOLDOWN/2)
```

2024-05-04 00:04 UTC, MaxwellJung requested changes
works well; just need some styling/formatting changes

2024-05-04 00:04 UTC, MaxwellJung commented on src/heroes/venture/drill_dash.opy
> +#!define ADJ_VENTURE_DRILL_DASH_COOLDOWN_BURROWED ADJ_VENTURE_DRILL_DASH_COOLDOWN / 2
```suggestion
#!define ADJ_VENTURE_DRILL_DASH_COOLDOWN_BURROWED (ADJ_VENTURE_DRILL_DASH_COOLDOWN/2)
```

in-line math should be surrounded with parenthesis

2024-05-04 00:04 UTC, MaxwellJung commented on src/heroes/venture/drill_dash.opy
> +		eventPlayer.setAbilityCooldown(Button.SECONDARY_FIRE, ADJ_VENTURE_DRILL_DASH_COOLDOWN)
```suggestion
		eventPlayer.setAbilityCooldown(Button.SECONDARY_FIRE, ADJ_VENTURE_DRILL_DASH_COOLDOWN)

```

add new line at EOF

2024-05-04 00:04 UTC, MaxwellJung commented on src/heroes/venture/drill_dash.opy
> +    @Condition not 0 == eventPlayer.getAbilityCooldown(Button.SECONDARY_FIRE)
```suggestion
    @Condition eventPlayer.getAbilityCooldown(Button.SECONDARY_FIRE) > 0
```

2024-05-04 00:04 UTC, MaxwellJung reviewed
works well; just need some styling/formatting changes

2024-05-04 00:11 UTC, MaxwellJung commented
actually I might close this PR because the cooldown slider seems to work already without this workshop code

2024-05-04 01:02 UTC, vwade commented
If you load 7HSKW, the cooldown is set to 75% but during a live game it reverts back to 8/4 seconds for some reason. Because of the uncertainty, at least until the reason can be fully known, I wanted to patch in the specific conditions to course-correct during gameplay.

Also, the condition was set to 0 < CD earlier, but that change wouldn't trigger the event. However the true/not-true setting worked as intended. It is a bit hacky, but functional! :)

2024-05-04 01:33 UTC, MaxwellJung commented
@ieToastie disable and reenable drill dash in venture hero settings in `7HSKW` and the cooldown gets fixed

2024-05-10 03:06 UTC, MaxwellJung commented
closing as the issue can be fixed without workshop code

2024-05-10 03:06 UTC, closed without merging