orisa, sombra, sojourn balance tweaks
6v6-Adjustments/6v6-adjustments-fork pull request #45
Opened 2024-05-16 03:13 UTC by ieToastie

| Orisa |
Base health reduced to 250 HP / 200 AP
Ultimate cost increased by 8%

| Sojourn |
Railgun primary fire maximum ammo reduced to 35
Power Slide cooldown increased to 9 seconds

| Sombra |
Virus cooldown increased to 8 seconds
Ultimate cost increased by 8%

2024-05-16 03:18 UTC, ieToastie commented
updated this commit to include the reduced minefield knockback

2024-05-16 03:53 UTC, MaxwellJung requested changes
everything looks good except ball change; see comment above

2024-05-16 03:53 UTC, MaxwellJung commented on src/heroes/wreckingball/init.opy
> +    eventPlayer.setKnockbackDealt(percent(ADJ_WRECKING_BALL_MINEFIELD_KNOCKBACK/OW2_WRECKING_BALL_MINEFIELD_KNOCKBACK))
This line causes pile driver to boop up much less. I think you need to revert the ball change,

2024-05-16 16:37 UTC, MaxwellJung approved these changes
lgtm

2024-05-16 16:38 UTC, merged

2024-05-20 20:20 UTC, MaxwellJung commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/6v6-Adjustments/6v6-adjustments/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: